### ISSUE TITLE
Specify file dependencies and make the file cacheable

### ISSUE THREAD

**Issue by rbhalla** [signal-ai/ng-require-loader#1]

**Comment by wesleyhall** [comment]
Haha! Little surprised to see this hit my inbox!! 

This issue must have been open for a while! ;)

**Comment by tragiclifestories** [comment]
#wontfix

**Comment by iggar** [comment]
![wat](https://user-images.githubusercontent.com/8342880/45372614-5ac81380-b5e5-11e8-8165-16bcd40cbe2e.jpg)

**Comment by wesleyhall** [comment]
I officially declare this event the “Bug #1 reunion”!!

**Comment by rbhalla** [comment]
@tragiclifestories we did eventually fix it, and it only took about 3 years.

https://github.com/SignalMedia/ng-require-loader/commit/b4c13a991761651d1a664547a863159c278232e0

**Comment by tragiclifestories** [comment]
woohoo!
![10x](https://pbs.twimg.com/profile_images/715711519267262465/L_PoMehS_400x400.jpg)
